tput bold
tput setaf 1
cat << "EOF"
           _______________________________
          | I have no clue what I'm doing |
          /-------------------------------
         /
¯\_(°‿‿°)_/¯

EOF

export PS1="\W \$"

alias showFiles='defaults write com.apple.finder AppleShowAllFiles YES; killall Finder /System/Library/CoreServices/Finder.app'
alias hideFiles='defaults write com.apple.finder AppleShowAllFiles NO; killall Finder /System/Library/CoreServices/Finder.app'

export PATH
